// app/terms/page.jsx

import Link from "next/link";

export const metadata = {
    title: "Terms & Conditions – JOSAA Master",
};

export default function TermsPage() {
    return (
        <div style={styles.wrapper}>
            <div style={styles.container}>
                <Link href="/dashboard" style={styles.back}>← Back to Home</Link>

                <h1 style={styles.title}>Terms &amp; Conditions</h1>
                <p style={styles.effective}>Effective Date: January 1, 2025</p>
                <p style={styles.intro}>
                    Welcome to <strong>JOSAA Master</strong>. By accessing or using our website, you agree to be
                    bound by these Terms and Conditions. Please read them carefully before using our services.
                </p>

                <Section number="1" title="Use of Service">
                    <p>
                        Our JOSAA predictor tool is provided for <strong>informational purposes only</strong>. We do not
                        guarantee the accuracy, completeness, or reliability of predictions. The tool is designed to
                        assist students in understanding admission trends based on historical data.
                    </p>
                </Section>

                <Section number="2" title="No Guarantee of Admission">
                    <p>
                        The results shown are based on historical cutoff data and algorithms. We are <strong>not
                            responsible</strong> for any admission decisions made by JOSAA, JoSAA authorities, IITs,
                        NITs, IIITs, or any other participating institutes. Actual cutoffs may vary each year.
                    </p>
                </Section>

                <Section number="3" title="User Responsibility">
                    <p>By using JOSAA Master, you agree to:</p>
                    <ul style={styles.list}>
                        <li>Provide accurate information such as rank, category, and preferences</li>
                        <li>Not misuse or attempt to disrupt the service in any manner</li>
                        <li>Not use automated tools, bots, or scripts to scrape or abuse the platform</li>
                        <li>Not attempt to reverse-engineer or copy our prediction algorithms</li>
                    </ul>
                </Section>

                <Section number="4" title="Intellectual Property">
                    <p>
                        All content, design, code, data, and features on this website are the exclusive property of
                        <strong> JOSAA Master</strong> and are protected under applicable intellectual property laws.
                        You may not copy, reproduce, distribute, or reuse any part of this website without prior
                        written permission.
                    </p>
                </Section>

                <Section number="5" title="Limitation of Liability">
                    <p>To the fullest extent permitted by law, JOSAA Master is not liable for:</p>
                    <ul style={styles.list}>
                        <li>Any incorrect or misleading predictions generated by the tool</li>
                        <li>Decisions made based on information provided on this platform</li>
                        <li>Any technical issues, downtime, or data loss</li>
                        <li>Any loss of opportunity related to college admissions</li>
                    </ul>
                </Section>

                <Section number="6" title="Paid Services">
                    <p>
                        Certain features of JOSAA Master may require payment. By purchasing any paid plan or feature,
                        you agree to our{" "}
                        <Link href="/refund" style={styles.link}>Cancellation &amp; Refund Policy</Link>.
                        All payments are processed securely via Razorpay.
                    </p>
                </Section>

                <Section number="7" title="Changes to Terms">
                    <p>
                        We reserve the right to update or modify these Terms at any time without prior notice.
                        Continued use of the website after any changes constitutes your acceptance of the new Terms.
                    </p>
                </Section>

                <Section number="8" title="Governing Law">
                    <p>
                        These Terms shall be governed by and construed in accordance with the laws of India.
                        Any disputes shall be subject to the exclusive jurisdiction of courts in India.
                    </p>
                </Section>

                <Section number="9" title="Contact">
                    <p>
                        For questions or concerns regarding these Terms, contact us at:{" "}
                        <a href="mailto:support@joSAA master.in" style={styles.link}>support@josaaMaster.in</a>
                        {" "}or visit our <Link href="/contact" style={styles.link}>Contact Page</Link>.
                    </p>
                </Section>
            </div>
        </div>
    );
}

function Section({ number, title, children }) {
    return (
        <div style={styles.section}>
            <h2 style={styles.sectionTitle}>{number}. {title}</h2>
            <div style={styles.sectionBody}>{children}</div>
        </div>
    );
}

const styles = {
    wrapper: {
        background: "#0f1117",
        minHeight: "100vh",
        padding: "60px 24px",
        color: "#e5e7eb",
        fontFamily: "'Segoe UI', system-ui, sans-serif",
    },
    container: {
        maxWidth: "780px",
        margin: "0 auto",
    },
    back: {
        color: "#60a5fa",
        textDecoration: "none",
        fontSize: "14px",
        display: "inline-block",
        marginBottom: "32px",
    },
    title: {
        fontSize: "clamp(28px, 5vw, 40px)",
        fontWeight: 800,
        color: "#f9fafb",
        marginBottom: "8px",
    },
    effective: {
        color: "#6b7280",
        fontSize: "14px",
        marginBottom: "24px",
    },
    intro: {
        color: "#9ca3af",
        lineHeight: 1.7,
        marginBottom: "40px",
        fontSize: "15px",
    },
    section: {
        marginBottom: "36px",
        borderLeft: "3px solid #2563eb",
        paddingLeft: "20px",
    },
    sectionTitle: {
        fontSize: "18px",
        fontWeight: 700,
        color: "#f3f4f6",
        marginBottom: "10px",
    },
    sectionBody: {
        color: "#9ca3af",
        lineHeight: 1.75,
        fontSize: "15px",
    },
    list: {
        paddingLeft: "20px",
        marginTop: "8px",
        lineHeight: 2,
    },
    link: {
        color: "#60a5fa",
        textDecoration: "underline",
    },
};